version: '3.8'

services:
  backend:
    build:
      context: .  # Root directory (CODETOCONQUER)
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://root:example@mongodb:27017/codetoconquer?authSource=admin
      - REDIS_URL=redis://localhost:6379
      - DOCKER_SOCKET=/var/run/docker.sock
    volumes:
      - code_submissions:/app/backend/submissions  # Adjusted to backend path
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:5.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "qwerty@123", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  mongo_data:
  redis_data:
  code_submissions: